.github/issue_template.md, .github/pull_request_template.md, README.md
[Issue] #1 
[Descriptions]
- 협업을 위한 규칙 추가
- 협업을 위한 규칙 설명을 `README.md`에 추가
=> Add rules and descriptions for collaboration

presenter/src/main/java/com/foke/together/presenter/screen/HomeScreen.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/HomeViewModel.kt
[Issue] #22
[Descriptions]
- HomeViewModel 추가 및 예제 작성
- HomeScreen과 HomeViewModel 연결
=> add viewmodel and flow example [#22]

data/src/main/java/com/foke/together/data/repository/AppPreferencesRepository.kt, data/src/main/proto/app_preferences.proto, domain/src/main/java/com/foke/together/domain/input/GetCameraSourceTypeInterface.kt, domain/src/main/java/com/foke/together/domain/input/GetSampleDataInterface.kt, domain/src/main/java/com/foke/together/domain/interactor/GetCameraSourceTypeUseCase.kt, domain/src/main/java/com/foke/together/domain/interactor/GetSampleDataUseCase.kt, domain/src/main/java/com/foke/together/domain/output/AppPreferenceInterface.kt
[Issue] #48
[Descriptions]
- GetCameraSourceTypeUseCase
- SetCameraSourceTypeUseCase
=> add usecase to set camera source type [#32]

gradle/libs.versions.toml, presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt, presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/CameraViewModel.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/SettingViewModel.kt, util/build.gradle.kts, util/src/main/java/com/foke/together/util/AppPolicy.kt, util/src/main/java/com/foke/together/util/ImageFileUtil.kt
[Issue] #29
[Descriptions]
- getExternalCameraIPUseCase를 이용한 Camera Preview 및 Capture
- MJpegView Start / Stop Stream
- 3초 타이머
=> Camera IP 촬영 및 UseCase

data/src/main/java/com/foke/together/data/datasource/remote/RemoteDataSource.java, data/src/main/java/com/foke/together/data/datasource/remote/WebClientApi.kt, data/src/main/java/com/foke/together/data/datasource/remote/WebClientModule.kt, data/src/main/java/com/foke/together/data/datasource/remote/WebDataSource.kt, data/src/main/java/com/foke/together/data/datasource/remote/dto/AccountRegisterRequest.kt, data/src/main/java/com/foke/together/data/datasource/remote/dto/AccountRegisterResponse.kt, data/src/main/java/com/foke/together/data/datasource/remote/dto/AccountSigninResponse.kt, data/src/main/java/com/foke/together/data/datasource/remote/dto/AccountWhoAmIResponse.kt, data/src/main/java/com/foke/together/data/datasource/remote/dto/S3PresignedUrlResponse.kt, data/src/main/java/com/foke/together/data/datasource/remote/interceptor/MockInterceptor.kt, data/src/main/java/com/foke/together/data/datasource/remote/interceptor/WebClientMockInterceptor.kt, data/src/main/java/com/foke/together/data/repository/RemoteRepository.kt, data/src/main/java/com/foke/together/data/repository/di/RepositoryModule.kt, domain/src/main/java/com/foke/together/domain/interactor/entity/AccountData.kt, domain/src/main/java/com/foke/together/domain/interactor/entity/PresignedFileData.kt, domain/src/main/java/com/foke/together/domain/output/RemoteRepositoryInterface.kt, external/src/main/java/com/foke/together/external/network/ExternalCameraModule.kt, external/src/main/java/com/foke/together/external/network/interceptor/ExternalCameraMockInterceptor.kt, util/src/main/java/com/foke/together/util/AppPolicy.kt
[Issue] #35
[Descriptions]
- 서버 통신 기능 베이스코드 구현
- https://4cuts.store/docs
=> add remote repository and api for server [#35]

external/src/main/java/com/foke/together/external/local/AndroidCameraDataSource.kt
[Issue] #58
[Descriptions]
- 추후 안드로이드 카메라 사용을 위한 data source 추가
=> add AndroidCameraDataSource [#58]

domain/src/main/java/com/foke/together/domain/interactor/CaptureWithExternalCameraUseCase.kt, external/src/main/java/com/foke/together/external/network/ExternalCameraApi.kt, external/src/main/java/com/foke/together/external/network/ExternalCameraDataSource.kt, external/src/main/java/com/foke/together/external/network/ExternalCameraModule.kt, external/src/main/java/com/foke/together/external/repository/ExternalCameraRepository.kt, presenter/src/main/java/com/foke/together/presenter/frame/FourCutFrame.kt, presenter/src/main/java/com/foke/together/presenter/frame/MakerFaireFrame.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/CameraViewModel.kt, util/src/main/java/com/foke/together/util/ImageFileUtil.kt, util/src/main/java/com/foke/together/util/TimeUtil.kt
[Issue] #58
[Descriptions]
- TODO: CameraScreen에서  filepath를 TimeUtil.getCurrentTimeSec() 로 전달
- filepath를 ScameraScreen -> GenerateScreen -> ShareScreen 로 전달
- 추후에는 filepath를 presenter에서 관리하지 않도록 해야 할듯
=> add file save code in CaptureWithExternalCameraUseCase [#58]

gradle/libs.versions.toml
=> update dependency versions [#85]

domain/src/main/java/com/foke/together/domain/interactor/AppInitUseCase.kt, presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/HomeViewModel.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/SettingViewModel.kt
- **[Issue]** #28
- state와 stateflow 분리
- AppInitUseCase 생성 후, 앱 실행 시 초기 작업 코드 구성
=> Bug fix. get and set ip address [#28]

data/src/main/java/com/foke/together/data/datasource/local/datastore/AppPreferencesSerializer.kt, presenter/src/main/res/values/strings.xml, util/src/main/java/com/foke/together/util/AppPolicy.kt, util/src/main/java/com/foke/together/util/TimeUtil.kt
=> do some chores [#85]

external/src/main/java/com/foke/together/external/camera/external/interceptor/BaseUrlInterceptor.kt, util/src/main/java/com/foke/together/util/retrofit/NetworkCall.kt
=> add network debug logs [#85]

presenter/src/main/java/com/foke/together/presenter/screen/ShareScreen.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/ShareViewModel.kt
- **[Issue]** #90
- QR코드가 정상적으로 생성되지 않던 문제 해결
=> hotfix. display qr code in share screen [#90]

presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
- **[Issue]** #28
- 텍스트박스 (토큰값 표시)
- 텍스트박스 (현재 로그인 정보 표시 위함)
- id입력창
- pw입력창
- 로그인 버튼
=> feat: add setting screen elements [#28]

presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt
- **[Issue]** #29
- camera screen 디자인 수정
=> fix camera screen [#29]

domain/src/main/java/com/foke/together/domain/interactor/CaptureWithExternalCameraUseCase.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/CameraViewModel.kt
- **[Issue]** #89
- external camera 촬영 UseCase 복구
- external camera 촬영 실패 시, preview 화면 캡쳐 사용
=> hotfix. take photo with external camera [#89]

presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt
- **[Issue]** #28 
- add capture interval input, to allow users take picture faster
=> feat: add capture interval input [#28]

presenter/src/main/java/com/foke/together/presenter/screen/GenerateTwoRowImageScreen.kt
- **[Issue]** #89
- 검은색 프레임 선택 시, 흰색 결과물이 나오는 버그 수정
=> hotfix. fix wrong cut frame color [#103]

presenter/src/main/java/com/foke/together/presenter/screen/SettingScreen.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/SettingViewModel.kt
- disable un-implemented code and do some chore
=> disable un-implemented code and do some chore [#85]

gradle/libs.versions.toml, util/src/main/java/com/foke/together/util/AppPolicy.kt
=> version up to v1.0.0 [#85]

presenter/src/main/java/com/foke/together/presenter/screen/CameraScreen.kt, util/src/main/java/com/foke/together/util/AppPolicy.kt
- **[Issue]** #116
- external camera 서버 통신 및 캡쳐 타이밍 시간 보정
=> bugfix. timing issue to capture with external camera [#116] 

presenter/src/main/java/com/foke/together/presenter/component/Basic.kt, presenter/src/main/java/com/foke/together/presenter/navigation/NavGraph.kt, presenter/src/main/java/com/foke/together/presenter/screen/HomeScreen.kt, presenter/src/main/java/com/foke/together/presenter/screen/InternalCameraScreen.kt, presenter/src/main/java/com/foke/together/presenter/screen/SelectFrameScreen.kt, presenter/src/main/java/com/foke/together/presenter/screen/ShareScreen.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/InternelCameraViewModel.kt, presenter/src/main/java/com/foke/together/presenter/viewmodel/SelectFrameViewModel.kt
- **[Issue]** #133 
- HomeScreen Color scheme 재수정.
- Skip SelectMethod Screen
- 카메리 화면 clip + 타이머 오버레이화면 추가
- bottomAppBar  적용
=> UI 가이드 확정 & 구현 [#133]
